name: Build Pull Request

on:
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - '.gitignore'
      - 'LICENSE'
      - 'README.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Gradle
        uses: GeyserMC/actions/setup-gradle-composite@master
        with:
          setup-java_java-version: 17

      - name: Build Thunder
        run: ./gradlew build

      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: Thunder
          path: bootstrap/build/libs/Thunder.jar